# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9ba605baf73ef51c6a17c900c66309d585f86fd3ad219d4495073e5ef0104c0bc5c5d26a6bf6262b29f7a515b6daec9fc4b194e0e07879e666b3b109db42335

test:
  secret_key_base: 2f02136e86e5371e99701522a8c8c44e1f3ff4865cd5a03d7610d76d715d463846bb3bf959b0606115ce013f3f544600362e6908b6379ae6ba551508c11f3664

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
